site_name: PvM Leeches Strategies
site_description: 'The Strategies for the PvM Leeches Discord server'
site_author: 'Friendliness'
docs_dir: docs/
repo_name: 'PvM-Leeches/Leeching-Strategies'
repo_url: 'https://github.com/PvM-Leeches/Leeching-Strategies'
nav:
    - Home: index.md
theme:
  name: 'material'
