site_name: PvM Leeches Strategies
site_description: 'The Strategies for the PvM Leeches Discord server'
docs_dir: docs/
repo_name: 'PvM-Leeches/Leeching-Strategies'
repo_url: 'https://github.com/PvM-Leeches/Leeching-Strategies'

theme:
  name: "material"
  font: Roboto
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.expand
    - toc.integrate 

  nav_style: dark

markdown_extensions:
  - admonition
  - toc:
      permalink: True


plugins:
  - search
  - include_dir_to_nav:
      sort_file: true
      sort_directory: true
  - autorefs
