name: Publish docs to Wiki

# Only trigger this action if there are changes pushed to the docs/** directory in the master branch
on:
  push:
    paths:
      - docs/**
    branches:
      - master

env:
  USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  USER_NAME: PvM-Leeches-Bot
  USER_EMAIL: rendomkrep@gmail.com
  OWNER: ${{ github.event.repository.owner.name }}
  REPOSITORY_NAME: ${{ github.event.repository.name }}

jobs:
  publish_docs_to_wiki:
    name: Publish docs to Wiki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # 1. Create folder named `tmp_wiki`
      # 2. Initialize Git
      # 3. Pull old Wiki content
      - name: Pull content from Wiki
        run: |
          mkdir tmp_wiki
          cd tmp_wiki
          git init
          git config user.name $USER_NAME
          git config user.email $USER_EMAIL
          git pull https://$USER_TOKEN@github.com/$OWNER/$REPOSITORY_NAME.wiki.git
      # 4. Synchronize differences between `docs` & `tmp_wiki`
      # 5. Push new Wiki content
      - name: Push content to wiki
        run: |
          rsync -av --delete docs/ tmp_wiki/ --exclude .git
          cd tmp_wiki
          git add .
          git commit -m "Update Wiki content"
          git push -f --set-upstream https://$USER_TOKEN@github.com/$OWNER/$REPOSITORY_NAME.wiki.git master


          
